# CamelCase format
autoFanControl: false
# Debug, Info, Warn, Error
logLevel: Info
sensors:
    # Video
    /nvidiagpu/0:
        - temperature: 30
          load: 20    
        - temperature: 50
          load: 40
        - temperature: 60
          load: 60
        - temperature: 70
          load: 100
          
    # CPU
    /lpc/it8631e/0:
        - temperature: 30
          load: 50
        - temperature: 50
          load: 60
        - temperature: 70
          load: 100
          
    # Case
    /lpc/it8631e/1:
        - temperature: 20
          load: 30
        - temperature: 30
          load: 40
        - temperature: 40
          load: 60
        - temperature: 70
          load: 100
default:
    - temperature: 20
      load: 30
    - temperature: 30
      load: 40
    - temperature: 40
      load: 60
    - temperature: 70
      load: 100
      
